### ISSUE TITLE
Why a zip with icons?

### ISSUE THREAD

**Issue by alzedd** [TheSquarePotatoMan/MaterialFire#3]
I don't get the point why I should download a zip and extract it. Cloning the repo in the chrome folder if the material icons are unzipped in  folder is enough. 

With the zip archive I am forced to do manual operations everytime I want to switch your css with another and viceversa. 

Having everything not zipped is easier when I just want to symlink my chrome folder to change the UserChrome.css

**Comment by TheSquarePotatoMan** [comment]
Sorry I'm new to github, I couldn't figure out how to add a folder instead of a zip. I'm changing it rn

**Comment by TheSquarePotatoMan** [comment]
Sorry, I'm a coding noob. Could you elaborate on what you mean by "manual operations every time"?, you only have to unzip it once right?

**Comment by alzedd** [comment]
Nope, if you update the icons I'll have to unzip that again. 

But, let's say I have symlinked your repo to my chrome directory, everytime I pull I'll have to unzip the icons. Having them unzipped in a folder makes every update automatic (no manual unzip necessary). :)
